### ISSUE TITLE
Super admin will need to be able to manage other tenants courses

### ISSUE THREAD

**Issue by dancgray** [deltanet/adapt_authoring#229]
"Tenant courses" dashboard currently only shows all (including non shared) courses for the tenant that the user is a member of. Would be useful for a super admin for be able to see all courses for different tenants.

**Comment by dancgray** [comment]
To do this the management screens will need to be able to select/filter courses by tenant. Will need new screens.

**Comment by deltanetdan** [comment]
No longer relevant due to AT refactor.
