### ISSUE TITLE
Ability to expand or collapse sections of the component editor similar to the new page editor

### ISSUE THREAD

**Issue by dancgray** [deltanet/adapt_authoring#295]
## Affected Area
Component editor/scaffold.

## Requested Feature
Have ability to expand or collapse sections of the component editor similar to the new page editor.

## Use Case
Developers want to see only the sections they need to edit without having to scroll.

## Current Workaround
Use the filter buttons that don't really work as expected.

## Additional Information
May be unnecessary once filter buttons work well.

**Comment by deltanetdan** [comment]
Users can already do this with the sidebar-fieldset-filter. Needs something more to make editing easier for non developers.
