### ISSUE TITLE
Investigate performance when editing a page: "page structure" 

### ISSUE THREAD

**Issue by dancgray** [deltanet/adapt_authoring#345]
Performance is quite slow on when editing a page ("page structure" ). This is mainly latency in the response from the server from component GET xhr calls. Specifically: http://localhost:5000/api/content/component?_parentId=5d381f2e59022c0e8294caa0

Investigate code efficiency improvements in server side content plugins.

**Comment by deltanetdan** [comment]
no longer relevant
