### ISSUE TITLE
Custom notify functionality has hardcoded 'Close' text in the themes notify.hbs

### ISSUE THREAD

**Issue by RobertPeek** [deltanet/adapt_authoring#86]

**Comment by dancgray** [comment]
https://github.com/deltanet/adapt-theme-delta/blob/master/templates/notify.hbs#L47

**Comment by dancgray** [comment]
@RobertPeek can this be closed now we have FW v2.2.5 themes?

**Comment by dancgray** [comment]
No longer relevant.
